version: '3.9'
name: tp1
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    external_links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    external_links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
