version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  initial_column_cleaner:
    container_name: initial_column_cleaner
    image: initial_column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
      - query_2_column_filter
      - query_5_column_filter

  filter_by_three_stopovers_1:
    container_name: filter_by_three_stopovers_1
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_2:
    container_name: filter_by_three_stopovers_2
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_3:
    container_name: filter_by_three_stopovers_3
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  query_handler:
    container_name: query_handler
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_column_filter:
    container_name: query_2_column_filter
    image: query_2_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - distance_calculator

  distance_calculator:
    container_name: distance_calculator
    image: distance_calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_5_column_filter:
    container_name: query_5_column_filter
    image: query_5_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy