version: '3.9'
name: tp1
services:
  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    restart: on-failure
    external_links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - initial_column_cleaner

  initial_column_cleaner:
    container_name: initial_column_cleaner
    image: initial_column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - filter_by_three_stopovers
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
      - filter_by_three_stopovers_4

  filter_by_three_stopovers:
    container_name: filter_by_three_stopovers
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_2:
    container_name: filter_by_three_stopovers_2
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_3:
    container_name: filter_by_three_stopovers_3
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_4:
    container_name: filter_by_three_stopovers_4
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  query_handler:
    container_name: query_handler
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1

  query_2_column_filter:
    container_name: query_2_column_filter
    image: query_2_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
  group_by_route:
    container_name: group_by_route
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport,destinationAirport
      - LISTENING_QUEUE=3_or_more_stop_overs
      - REDUCERS_AMOUNT=2
      - QUEUE_GROUP_BY=group_by_route_queue
      - INPUT_QUEUE=group_by_route
