version: '3.9'
name: tp1
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 15672:15672
    environment:
      - RABBITMQ_LOGS=rabbit.log
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 50s

  client:
    container_name: client
    image: client:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - server

  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    links:
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  initial_column_cleaner:
    container_name: initial_column_cleaner
    image: initial_column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
      - query_2_column_filter_1
      - query_2_column_filter_2
      - query_5_column_filter

  initial_column_cleaner_2:
    container_name: initial_column_cleaner_2
    image: initial_column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
      - filter_by_three_stopovers_4

  initial_column_cleaner_3:
    container_name: initial_column_cleaner_3
    image: initial_column_cleaner:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - filter_by_three_stopovers_1
      - filter_by_three_stopovers_2
      - filter_by_three_stopovers_3
      - filter_by_three_stopovers_4

  filter_by_three_stopovers_1:
    container_name: filter_by_three_stopovers_1
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_2:
    container_name: filter_by_three_stopovers_2
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_3:
    container_name: filter_by_three_stopovers_3
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  filter_by_three_stopovers_4:
    container_name: filter_by_three_stopovers_4
    image: filter_by_three_stopovers:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - query_handler

  query_handler:
    container_name: query_handler
    image: query_handler:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_2_column_filter_1:
    container_name: query_2_column_filter_1
    image: query_2_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - distance_calculator_1
      - distance_calculator_2

  query_2_column_filter_2:
    container_name: query_2_column_filter_2
    image: query_2_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - distance_calculator_1
      - distance_calculator_2

  group_by_route:
    container_name: group_by_route
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport,destinationAirport
      - INPUT_EXCHANGE=3_or_more_stop_overs
      - REDUCERS_AMOUNT=2
      - QUEUE_GROUP_BY=group_by_route_queue
      - LISTENING_QUEUE=group_by_route
      - INPUT_QUEUE=
    depends_on:
      rabbitmq:
        condition: service_healthy

  reducer_group_by_route_1:
    container_name: reducer_group_by_route_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_1
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on:
      rabbitmq:
        condition: service_healthy

  reducer_group_by_route_2:
    container_name: reducer_group_by_route_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=route
      - INPUT_QUEUE=group_by_route_queue_2
      - OUTPUT_QUEUE=output_3
      - QUERY_NUMBER=3
    depends_on:
      rabbitmq:
        condition: service_healthy

  distance_calculator_1:
    container_name: distance_calculator_1
    image: distance_calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  distance_calculator_2:
    container_name: distance_calculator_2
    image: distance_calculator:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      rabbitmq:
        condition: service_healthy

  query_5_column_filter:
    container_name: query_5_column_filter
    image: query_5_column_filter:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - group_by_airport_1

  group_by_airport_1:
    container_name: group_by_airport_1
    image: group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_EXCHANGE=
      - REDUCERS_AMOUNT=2
      - QUEUE_GROUP_BY=group_by_airport_queue
      - INPUT_QUEUE=mode_calculation
    depends_on:
      - reducer_group_by_airport_1
      - reducer_group_by_airport_2

  reducer_group_by_airport_1:
    container_name: reducer_group_by_airport_1
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_1
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on:
      rabbitmq:
        condition: service_healthy

  reducer_group_by_airport_2:
    container_name: reducer_group_by_airport_2
    image: reducer_group_by:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - FIELD_GROUP_BY=startingAirport
      - INPUT_QUEUE=group_by_airport_queue_2
      - OUTPUT_QUEUE=output_5
      - QUERY_NUMBER=5
    depends_on:
      rabbitmq:
        condition: service_healthy